### ISSUE TITLE
Sign function to send parameters to ledger

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-ledger-js#8]
Send the transaction parameters to the ledger device and get the signed transaction after the user confirmed the transaction on the device.

**Comment by ehsueh** [comment]
Refer to issue #9 for initializing the device. For params, see examples in issues #2 
 to #7  or `index.js` at this [repo](https://github.com/ehsueh/mvs-ledger-js/)
```
const transaction = await ledger.createPaymentTransactionNew(
        ledger_inputs,
        associatedKeysets,
        changePath,
        outputsScript,
        locktime,
        sigHash,
        segwit,
        initialTimestamp,
        additionals,
        expiryHeight,
        options
)
```
