### ISSUE TITLE
Get public key from device

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-ledger-js#9]
Get the public key that can be used to generate the wallets addresses from the ledger device

**Comment by ehsueh** [comment]
Import requirements:
```
require('babel-polyfill')
const TransportHID = require('@ledgerhq/hw-transport-node-hid').default;
const BtcApp = require('./ledgerjs-hw-app-btc').default;
```
A function to get the ledger device:
```
const getDevice = async () => {
    let transport = await TransportHID.create();
    let ledger = new BtcApp(transport);
    ledger.close = () => transport.close();
    console.log(ledger)
    return ledger;
};
```
To get a public address, provide a derivation path to the `getWalletPublicKey()` function. `walletInfo` will contain a Metaverse address `bitcoinAddress`, chain code `chainCode` and the public key `publicKey`
```
const path = "44'/2302'/1'/0/0";
const ledger = await getDevice();
const walletInfo = await ledger.getWalletPublicKey(path);
```
To get the master extended public key for Metaverse, use Metaverse's slip number (BIP0044):
```
const xpub = await ledger.getWalletPublicKey("44'/2302'/").publicKey;
```
